version: "3"

services:
  app:
    image: node:lts
    container_name: react-hooks-sample
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: volume
        source: node_modules
        target: /src/sample-app/node_modules
    working_dir: "/src"
    ports:
      - 3000:3000
volumes:
  node_modules:
